### PR TITLE
Update genOrdCat with non-proportional odds

### PR DESCRIPTION
**Pull request by kgoldfeld**
@assignUser I have updated the function `genOrdCat` that allows two new arguments `npVar` and `npAdj` to introduce non-proportionality into the generation of ordinal categorical data. This included creating a new `Rcpp` function `chkNonIncreasing` to quickly verify that "adjusted" logistic thresholds are well behaved (i.e. properly ordered), as well as adding some basic argument checking and unit tests (I am sure these can be improved). Finally, I updated the vignette. I think those are all the changes. If you want to take a look, let me know. Or if not, also let me know.

### CODE REVIEW

**Comment by kgoldfeld** [comment]
@assignUser I could definitely use some help figuring out the failed checks - any insight would be helpful.

**Comment by assignUser** [comment]
So the CB test fail due to changes in the API that I have to update in the scripts. 
The fail on macos I'm not sure about, I'll have a look.
Afterwards I'll look into your changes :)

**Comment by assignUser** [comment]
@kgoldfeld Ok, I fixed the issue with touchstione. I thought the macos issue might be a fluke but it happend again :( I'll have to investigate.

**Comment by kgoldfeld** [comment]
You fixed it!

**Comment by assignUser** [comment]
@kgoldfeld yes! I also updated all workflows to use the new action to install r and the dependencies  (#130) Which will make everything quicker and much easier to read and maintain!

**Comment by assignUser** [comment]
@kgoldfeld I didn't have the time too check the code in depth but a quick skim looks good! I will look into it this weekend :)

**Comment by assignUser** [comment]
@kgoldfeld I added some cosmetics but I think overall we can merge this now :)

**Comment by kgoldfeld** [comment]
Thanks.

**Pull request merged**
