### PR TITLE
Resolve native symbol registration complaint

### PR DESCRIPTION
**Pull request by coatless**
The PR resolves the native symbol registration complaint and fixes a few other notes raised during `R CMD check`.

winbuilder `R CMD check` verifying the fix:

```
* using log directory 'd:/RCompile/CRANguest/R-devel/simstudy.Rcheck'
* using R Under development (unstable) (2017-06-29 r72864)
* using platform: x86_64-w64-mingw32 (64-bit)
* using session charset: ISO8859-1
* checking for file 'simstudy/DESCRIPTION' ... OK
* checking extension type ... Package
* this is package 'simstudy' version '0.1.3'
* checking CRAN incoming feasibility ... NOTE
Maintainer: 'Keith Goldfeld <---------->'
Possibly mis-spelled words in DESCRIPTION:
  MCAR (14:17)
  Missingness (13:24)
  NMAR (14:28)
  covariates (10:27)
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking whether package 'simstudy' can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking 'build' directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* loading checks for arch 'i386'
** checking whether the package can be loaded ... OK
** checking whether the package can be loaded with stated dependencies ... OK
** checking whether the package can be unloaded cleanly ... OK
** checking whether the namespace can be loaded with stated dependencies ... OK
** checking whether the namespace can be unloaded cleanly ... OK
** checking loading without being on the library search path ... OK
** checking use of S3 registration ... OK
* loading checks for arch 'x64'
** checking whether the package can be loaded ... OK
** checking whether the package can be loaded with stated dependencies ... OK
** checking whether the package can be unloaded cleanly ... OK
** checking whether the namespace can be loaded with stated dependencies ... OK
** checking whether the namespace can be unloaded cleanly ... OK
** checking loading without being on the library search path ... OK
** checking use of S3 registration ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd line widths ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking line endings in C/C++/Fortran sources/headers ... OK
* checking compiled code ... OK
* checking installed files from 'inst/doc' ... OK
* checking files in 'vignettes' ... OK
* checking examples ...
** running examples for arch 'i386' ... [2s] OK
** running examples for arch 'x64' ... [3s] OK
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in 'inst/doc' ... OK
* checking re-building of vignette outputs ... [24s] OK
* checking PDF version of manual ... OK
* DONE
```

Fixed:

```
NOTE
Found the following hidden files and directories:
  revdep/.cache.rds
These were most likely included in error. See section 'Package
structure' in the 'Writing R Extensions' manual.

CRAN-pack does not know about
  revdep/.cache.rds

NOTE
File
  LICENSE
is not mentioned in the DESCRIPTION file.
Non-standard files/directories found at top level:
  'README.Rmd' 'cran-comments.md' 'revdep'

NOTE
File 'simstudy/libs/x64/simstudy.dll':
  Found no calls to: 'R_registerRoutines', 'R_useDynamicSymbols'

It is good practice to register native routines and to disable symbol
search.
```

### CODE REVIEW

**Comment by kgoldfeld** [comment]
Thanks for checking into this. Did you edit the RcppExports.cpp manually? What would happen if I changed any of the src code (say, if I added a new Rcpp function)? Would I have to edit manually again? And before, I was getting no Note with the winbuilder, only when I run the R CMD check as part of the package released process. Do you think this will go away, or do I need to use the development version of R?

**Comment by coatless** [comment]
@kgoldfeld:

1. No. As of Rcpp 0.12.11, the necessary registration plumbing is automatically generated by `compileAttributes()` within Rcpp. (There are a few known issues that crept up, but have since been addressed within the development build of Rcpp that should be rolled out mid-July assuming the cadence of every two months).
2. As before with new additions or subtractions of functions, just re-run the `compileAttributes()` (or build the package within RStudio) to have the registration setup be updated. There is no need for manual edits.
3. I think this is a bug on certain versions of Windows. I wasn't able to reproduce this on my development VM. The main check that _must_ be passed is in regard to the winbuilder service. Though, you probably should upgrade to R 3.4.1 (released today!)

**Comment by kgoldfeld** [comment]
I merged all of your commits. While it passed the devtools::build_win() test, the check on my local windows computer is still generating the same note. Would you suggest I go ahead and submit the package anyways?

build_win() results:

* using log directory 'd:/RCompile/CRANguest/R-devel/simstudy.Rcheck'
* using R Under development (unstable) (2017-07-01 r72871)
* using platform: x86_64-w64-mingw32 (64-bit)
* using session charset: ISO8859-1
* checking for file 'simstudy/DESCRIPTION' ... OK
* checking extension type ... Package
* this is package 'simstudy' version '0.1.3'
* checking CRAN incoming feasibility ... NOTE
Maintainer: 'Keith Goldfeld <Keith.Goldfeld@nyumc.org>'

Possibly mis-spelled words in DESCRIPTION:
  MCAR (14:17)
  Missingness (13:24)
  NMAR (14:28)
  covariates (10:27)

* checking for unstated dependencies in examples ... OK
* checking line endings in C/C++/Fortran sources/headers ... OK
* checking compiled code ... OK
* checking installed files from 'inst/doc' ... OK
* checking files in 'vignettes' ... OK
* checking examples ...
** running examples for arch 'i386' ... [3s] OK
** running examples for arch 'x64' ... [4s] OK
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in 'inst/doc' ... OK
* checking re-building of vignette outputs ... [25s] OK
* checking PDF version of manual ... OK
* DONE
Status: 1 NOTE

devtools::check(args = c('--use-valgrind')) results:

See
  'C:/Users/goldfk01/Box Sync/R Projects/simstudy.Rcheck/00check.log'
for details.


checking compiled code ... NOTE
File 'simstudy/libs/x64/simstudy.dll':
  Found no calls to: 'R_registerRoutines', 'R_useDynamicSymbols'

It is good practice to register native routines and to disable symbol
search.

See 'Writing portable packages' in the 'Writing R Extensions' manual.
R CMD check results
0 errors | 0 warnings | 1 note 

R CMD check succeeded

**Comment by coatless** [comment]
Aye. I think there is some issue with the local Windows for _R_ installation. If it is passing at the winbuilder service, then all is well. My development VM was able to pass with flying colors. I think I'll likely try to track down the issue and [open a bug ticket](https://bugs.r-project.org/bugzilla3/) with _R_.

Did you by chance grab R 3.4.1? (You should modify the `cran-comments.md` to reflect the latest version.)

**Comment by kgoldfeld** [comment]
I did update to 3.4.1 at the end of last week.

Now I am running devtools::release(), and it is hanging just after it loads the package. Very weird.

**Comment by coatless** [comment]
@kgoldfeld Odd. Where is it hanging?

**Comment by kgoldfeld** [comment]
After the spelling check, it starts loading simstudy, and then I get this question mark (?). Here is what I get:

Building and checking simstudy ===========================================
Updating simstudy documentation
Loading simstudy
?

**Comment by coatless** [comment]
Oh... When you upgraded, did you reinstall the _R_ packages you use? 

e.g. 

```r
install.packages(c("Rcpp","tidyverse"))
```

?

**Comment by kgoldfeld** [comment]
Does one need to reinstall everything? I've never had to do that before.

**Comment by coatless** [comment]
When you upgrade to different _R_ versions it sometimes is required. Let me quickly build the branch and do a test run.

**Comment by coatless** [comment]
Okay. I was able to recreate it. This is an artifact of R 3.4.1 having an interaction with devtools. Specifically, the documentation feature... See https://github.com/hadley/devtools/issues/1537

```r
# Packages required for devtools::release()
install.packages(c("roxygen2", "hunspell","rversions")) 
```

To "escape it" simply press enter and then x. If you would like, I could do the release process for you if this doesn't work.

devtools_interaction

**Comment by kgoldfeld** [comment]
So - it is my use of _Package that is causing problems. I'll just get rid of that and try it all again.

**Comment by coatless** [comment]
No. The issue is there was a slight regression with _R 3.4.1_ and how `roxygen2` parses comments (per the linked devtools issue ticket). Your use of packages is 100% okay.

Right now, to use the `devtools::release()` feature, you must answer the `?` prompt with <kbd>return</kbd> and then some letter (in my case I chose <kbd>x</kbd>). After doing this, the  process will then proceed normally.

**Comment by kgoldfeld** [comment]
OK - I have submitted - hopefully that issue won't give me any problems this time around. And hopefully it will be fixed in the future.

Thanks so much for your help. You've been like a guardian angel in this process. I don't want to bug you too much in the future - but is it OK with you if I reach out with similar problems?

**Comment by coatless** [comment]
Sure. I can't guarantee how much time I will have available though. Summer is a definite beast than the school year.

**Comment by kgoldfeld** [comment]
Now that I have your attention, was wondering if you'd ever seen anything like this. I have a Mac running, OS 10.11.6 (El Capitan) and realized I was running R 3.3.2. So, I went to upgrade to 3.4.1, but that doesn't appear to be out yet, so I went for 3.4.0. And I am getting this nasty message when I start up R:

### *** caught segfault ***
address 0x18, cause 'memory not mapped'

Traceback:
 1: dyn.load(file, DLLpath = DLLpath, ...)
 2: library.dynam(lib, package, package.lib)
 3: loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]])
 4: asNamespace(ns)
 5: namespaceImportFrom(ns, loadNamespace(j <- i[[1L]], c(lib.loc,     .libPaths()), versionCheck = vI[[j]]), i[[2L]], from = package)
 6: loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]])
 7: namespaceImport(ns, loadNamespace(i, c(lib.loc, .libPaths()),     versionCheck = vI[[i]]), from = package)
 8: loadNamespace(package, lib.loc)
 9: doTryCatch(return(expr), name, parentenv, handler)
10: tryCatchOne(expr, names, parentenv, handlers[[1L]])
11: tryCatchList(expr, classes, parentenv, handlers)
12: tryCatch({    attr(package, "LibPath") <- which.lib.loc    ns <- loadNamespace(package, lib.loc)    env <- attachNamespace(ns, pos = pos, deps)}, error = function(e) {    P <- if (!is.null(cc <- conditionCall(e)))         paste(" in", deparse(cc)[1L])    else ""    msg <- gettextf("package or namespace load failed for %s%s:\n %s",         sQuote(package), P, conditionMessage(e))    if (logical.return)         message(paste("Error:", msg), domain = NA)    else stop(msg, call. = FALSE, domain = NA)})
13: library(reshape2)
14: .First()

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace

**Comment by kgoldfeld** [comment]
No worries about my last question - of course it was related to my packages. I seem to be back up and running.

**Comment by coatless** [comment]
The 3.4.x line is vastly different than the 3.3.x line with respect to compiled code. As a result, all packages must be reinstalled when you install R 3.4.x. 

You may just want to do a clean removal of _R_ with:

https://freemacsoft.net/appcleaner/

Then reinstall _R_ and the packages.

**Pull request merged**
