### PR TITLE
New gha

### PR DESCRIPTION
**Pull request by assignUser**

### CODE REVIEW

**Comment by kgoldfeld** [comment]
Can you explain a little bit what all of this is about?

**Comment by assignUser** [comment]
I simplified the github action script for the continous benchmarking and wanted to test it but accidentaly opened a pr from my test fork to here. When I actually wanted to open a pr within the fork to test it out :)

**Comment by kgoldfeld** [comment]
You already merged back on kgoldfeld/simstudy?

**Comment by assignUser** [comment]
No, this was on my fork of simstudy which I use to test stuff. Has no implications for this repository. 

Any changes I actually want to implement I will bring over in a separate PR

**Comment by kgoldfeld** [comment]
That is what I thought - carry on.

**Pull request closed without merging**
