### PR TITLE
Issue 102

### LINKED ISSUE #102: vector/matrix reference within double dot notation
It would be nice to be able to refer to vectors and matrices in a dynamic way in a formula that uses double do notation. I think this is easiest to see in a simple example. I have two vectors of length 2 (`b_1` and `b_2`) and a `2 X 2`  matrix `b_12`:

```r
library(simstudy)

b_0 <- 0
b_1 <- c(-3, 3)
b_2 <- c(-1, 1)
b_12 <- matrix(c(-1, -1, -1, 3), nrow = 2)
```

Each individual is assigned a value of 1 or 2 for factor `a` and for factor `b`:
```r
d1 <- defData(varname = "a", formula = ".5;.5", variance = "1;2", dist = "categorical")
d1 <- defData(d1, varname = "b", formula = ".5;.5", variance = "1;2", dist = "categorical")

set.seed(1)
dx <- genData(3, d1)
dx
#>    id a b
#> 1:  1 2 1
#> 2:  2 2 2
#> 3:  3 1 1
```

Now, I want to create an outcome variable that references these vectors and matrix, and pulls from the cell based on the values of `a` and `b`. Here is a non-simstudy solution:

```r
dx[, y := b_0 + b_1[a] + b_2[b] + b_12[a, b], keyby = id]
dx
#>    id a b  y
#> 1:  1 2 1  1
#> 2:  2 2 2  7
#> 3:  3 1 1 -5
```

It would be nice to be able to use double dot notation to refer to the vectors and matrix from within the the dataDef table, like this:

```r
d1 <- defData(d1, varname = "y", formula = "..b_0 + ..b_1[a] + ..b_2[b] + ..b_12[a, b]", dist="nonrandom")
d1
#>    varname                                    formula variance        dist         link
#> 1:       a                                      .5;.5      1;2 categorical     identity
#> 2:       b                                      .5;.5      1;2 categorical     identity
#> 3:       y ..b_0 + ..b_1[a] + ..b_2[b] + ..b_12[a, b]        0   nonrandom     identity
```

It doesn't quite work:

```r
set.seed(1)
genData(3, d1)
#>    id a b  y
#> 1:  1 2 1  1
#> 2:  1 2 1  5
#> 3:  1 2 1  1
#> 4:  2 2 2  3
#> 5:  2 2 2  7
#> 6:  2 2 2  3
#> 7:  3 1 1 -5
#> 8:  3 1 1 -5
#> 9:  3 1 1 -5
```

### LINKED ISSUE #105: Working with vectorized variables in formulas
I was just generating data where I found it useful to vectorize an operation, but I could not get it to work with simstudy. This is just a note in case someone has time to look into this issue.

This is what I was trying to do, which obviously works fine:

```
library(simstudy)
set.seed(1)

d <- defData(varname = "a", formula = 0.6, dist="binary")
d <- defData(d, varname = "b", formula = 0.4, dist="binary")
d <- defData(d, varname = "c", formula = 0.3, dist="binary")
d <- defData(d, varname = "theta", formula = "..tau[1]*a + ..tau[2]*b + ..tau[3]*c", dist = "nonrandom")

tau <- rnorm(3, 0, 1)
tau
#> [1] -0.6264538  0.1836433 -0.8356286

genData(4, d)
#>    id a b c      theta
#> 1:  1 0 0 1 -0.8356286
#> 2:  2 0 0 0  0.0000000
#> 3:  3 0 1 1 -0.6519853
#> 4:  4 1 0 1 -1.4620824
```

But I wanted to simplify the equation for `theta` by vectorizing, defining the formula as `t(..tau) %*% c(a, b, c)`. This returned an error when I tried generating the data:

```
d <- updateDef(d, changevar = "theta", newformula = "t(..tau) %*% c(a, b, c)")

genData(4, d)
#> Error in t(..tau) %*% c(a, b, c): non-conformable arguments
```

However, more generally, this can work as long as no variables are referenced (which obviously is not so useful):

```
d <- updateDef(d, changevar = "theta", newformula = "t(..tau) %*% c(1, 1, 1)")

genData(4, d)
#>    id a b c     theta
#> 1:  1 1 1 1 -1.278439
#> 2:  2 1 1 0 -1.278439
#> 3:  3 1 1 1 -1.278439
#> 4:  4 1 0 0 -1.278439
```

This is really a `data.table` issue, so my guess is we can fix it in `simstudy`. Here is a `data.table` example that generates the same error.

```
d <- d[1:3]
x <- genData(4, d)
x
#>    id a b c
#> 1:  1 0 0 0
#> 2:  2 1 0 1
#> 3:  3 1 1 0
#> 4:  4 0 1 0

x[, t(tau) %*% c(a, b, c)]
#> Error in t(tau) %*% c(a, b, c): non-conformable arguments
```

However, if we execute the formula using `keyby`, it works. So, we might want to make sure we are doing this in `simstudy`:

```
x[, t(tau) %*% c(a, b, c), keyby = id]
#>    id         V1
#> 1:  1  0.0000000
#> 2:  2 -1.4620824
#> 3:  3 -0.4428105
#> 4:  4  0.1836433
```

### PR DESCRIPTION
**Pull request by assignUser**
Closes #102 
Closes #105 

This is ready but I do want to merge the touchstone changes back into this from main to check how/if the performance changes.
I added some tests and looked over everything again and it looks good to me. Let me know what you think.

### CODE REVIEW

**Comment by kgoldfeld** [comment]
Should we be worried that all these checks failed?

**Comment by assignUser** [comment]
> Should we be worried that all these checks failed?

I'll have a look after #112

**Comment by kgoldfeld** [comment]
I built and installed from issue-102 branch to see how things are working. R crashes when I run this simple code

```r
b_0 <- 0
b_1 <- c(-3, 3)
b_2 <- c(-1, 1)
b_12 <- matrix(c(-1, -1, -1, 3), nrow = 2)

d1 <- defData(varname = "a", formula = ".5;.5", variance = "1;2", dist = "categorical")
d1 <- defData(d1, varname = "b", formula = ".5;.5", variance = "1;2", dist = "categorical")

set.seed(1)
dx <- genData(3, d1)
```

But now, I can't build and install anything from within RStudio - getting this message:

```r
==> Rcpp::compileAttributes()

* Updated R/RcppExports.R

==> R CMD INSTALL --no-multiarch --with-keep.source simstudy

* installing to library ‘/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library’
* installing *source* package ‘simstudy’ ...
** using staged installation
make: Nothing to be done for `all'.
** libs
installing to /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/00LOCK-simstudy/00new/simstudy/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location

 *** caught segfault ***
address 0x0, cause 'invalid permissions'
An irrecoverable exception occurred. R is aborting now ...
sh: line 1: 17735 Segmentation fault: 11  R_TESTS= '/Library/Frameworks/R.framework/Resources/bin/R' --no-save --no-restore --no-echo 2>&1 < '/var/folders/jr/19fz7v9976gbf62sf66f7zz40000gq/T//RtmpudpQAP/file453012e04ccd'
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/simstudy’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/simstudy’

Exited with status 1.
```

This might take me a little while to figure out.

**Comment by assignUser** [comment]
@kgoldfeld try updateing RCPP I have recently switched over to linux so all my packages are completley uptodate and RCPP automatically this: https://github.com/kgoldfeld/simstudy/pull/113/files#diff-13dc68d7d985baff5c1cac41e1471ed9fe4db63a2bea80c2cdf20fd795541062R8-R12

That is the most likely cause I think...

**Comment by assignUser** [comment]
I can run the code posted above without issue... but the error with the vignette is caused by it not being to able to run a mixture dist correctly, this is a data.table issue I dont fully understand, maybe you can have a look and let me know what the issue is?
```r
defblk <- defData(varname = "blksize", 
   formula = "..sizes[1] | .5 + ..sizes[2] | .5", dist = "mixture")
sizes <- c(2, 4)
genData(1000, defblk)
```
gives this error 
```
Error in `[.data.table`(dtSim, , `:=`(newVar, eval(parse(text = as.character(formula2parse)))),  : 
  Supplied 1000 items to be assigned to group 1 of size 1 in column 'newVar'. The RHS length must either be 1 (single values are ok) or match the LHS length exactly. If you wish to 'recycle' the RHS please use rep() explicitly to make this intent clear to readers of your code.
```

**Comment by kgoldfeld** [comment]
Just wanted to let you know that I am able to build and install again. And the vectorization does not crash my computer any more - it seems to work. I'll check out the other issue this afternoon.

**Comment by kgoldfeld** [comment]
That mixture error is weird - it works just fine under the current CRAN version as well as the development branch (main). Something you did to enable the vectorization is wrecking havoc. I guess you know that already? And just trying to understand what is going wrong? I'll look into it more.

**Comment by assignUser** [comment]
Yes it is the `keyby` argument in the data.table formula. I have to read up on data table more but what is happening, I think is that `keyby = id` makes each row a separate group but the formula for the mixture gives a n-length vector when evaluatef.

Usually we would just use an if to not use keyby for those cases.... the issue is that I don now how we could easily detect the difference in the formulas...

**Comment by assignUser** [comment]
So... I have what I would loath to call a solution... but well here it is: 
```r
res <- with(e, {
      expr <- parse(text = as.character(formula2parse))
      tryCatch(
        expr = dtSim[, newVar := eval(expr), keyby = def_id],
        error = function(err) {
          if (grepl("RHS length must either be 1", gettext(err), fixed = T)) {
            dtSim[, newVar := eval(expr)]
          } else {
            stop(gettext(err))
          }
        }
      )
      copy(dtSim$newVar)
    })
```
It is not pretty but it works xD in view of simstudy 1.0 (or the "overhaul ) which will change the whole system I think this solution is adequate for now. 

I have pushed the changes, let me know if you think this is acceptable for now.

p.s. I (or rather devtools) removed the knitted vignettes from the /vignettes folder as is expected by cran(https://blog.r-hub.io/2020/06/03/vignettes/#overview-of-vignettes-states)

**Comment by assignUser** [comment]
rebuilding worked on my end so I don't know why the gha checks fail, could you check out this branch and test if you can build the vignettes?

**Comment by assignUser** [comment]
@kgoldfeld my "solution" passes all checks :D give it a try and if everything is ok please merge #112 so I can merge it into this branch too and we can check out the performance implications.

**Pull request merged**
