### PR TITLE
Update to 0.2.0

### PR DESCRIPTION
**Pull request by assignUser**

### CODE REVIEW

**Comment by kgoldfeld** [comment]
Just to be clear - this is going from main to release?

**Comment by assignUser** [comment]
yes

**Comment by kgoldfeld** [comment]
There are conflicts preventing a merge ... should I "resolve conflicts"?

**Comment by assignUser** [comment]
You can do it if you want :)

**Comment by kgoldfeld** [comment]
What will happen when I resolve the conflicts? Main will overwrite release?

**Comment by assignUser** [comment]
Yes, in this case we want to overwritte release from main.

**Comment by kgoldfeld** [comment]
I'm confused on resolving the conflicts, since I am not sure what would be overwriting what. It seems like it would be overwriting main from release.

Is this something you can do?

**Comment by assignUser** [comment]
Looks like I can't because of the branch protection. Post a screenshot of
one of the conflicts and I'll explain the situation. The way it looks is
indeed confusing.

**Comment by kgoldfeld** [comment]
This is unfortunate, but maybe it isn't that bad. I am guessing I need to keep everything between 

<<<<<<< main and the next ===========

and delete everything between =========== and >>>>>>> release

I can send more screen shots of others if that would help.


Screen Shot 2020-10-06 at 2 02 21 PM


Here's another:

Screen Shot 2020-10-06 at 2 04 26 PM

The rest are more less like this.

**Comment by assignUser** [comment]
Yes that's exactly right.

kgoldfeld <notifications@github.com> schrieb am Di., 6. Okt. 2020, 20:08:

**Comment by kgoldfeld** [comment]
Actually almost done - I just went for it.

**Comment by kgoldfeld** [comment]
When I finished resolving the conflicts, it asked me to commit changes, which would mean that I would be updating main. I assume that is fine because we are just fixing these files - but just want to confirm.

**Comment by assignUser** [comment]
👍 nice

kgoldfeld <notifications@github.com> schrieb am Di., 6. Okt. 2020, 20:53:

**Comment by kgoldfeld** [comment]
So - just to doubly confirm - I am going to commit these changes back to main, and then will merge all of main into release.

**Comment by assignUser** [comment]
Yes that should be fine, as you kept all "changes" from main nothing really
changed. And 0.2.0 was tagged so no issue there

kgoldfeld <notifications@github.com> schrieb am Di., 6. Okt. 2020, 21:06:

**Comment by kgoldfeld** [comment]
At some point, you'll have to explain "tagging." I am just waiting for checks to complete.

**Pull request merged**
