### PR TITLE
Fixing rounding bug in .gencat

### PR DESCRIPTION
**Pull request by kgoldfeld**
This is a fix for Issue #135.

### CODE REVIEW

**Comment by assignUser** [comment]
Should we mention the rounding in the gencat documentation? 12 digits should be enough for most anyone but you never know...

**Comment by assignUser** [comment]
@kgoldfeld the failed check you might have an email about was caused by the action that sets up the r dependencies, I think it is a timeout issue or something as I had it yesterday and re-running the check solved it.

**Comment by kgoldfeld** [comment]
I will add documentation to make it clear, though it would be pretty useless to simulate data based on a probability of 1e-12. I just tested it out with `rbinom(1e8, 1, prob = 1e-12), and ran that 100 times, so we effectively had 1e10 (10 billion) tosses, and no successes. Maybe with a trillion tosses, we'll see one - at least that is what we expect. I am not sure `simstudy` can handle a trillion tosses.

**Comment by assignUser** [comment]
Wow :grin:

**Comment by kgoldfeld** [comment]
Any objections to my merging (assuming that last check passes)?

**Review by assignUser — APPROVED** [review]
Looks good to me!

**Pull request merged**
